### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by m-planck** [452/USBHIDTerminal#1]
Hi,
what is the license on this project? You did not specify GPL or MIT.
Is there a documentation of the commands? In your screen shot, there is a $, a hex number 0x80 and a #. What is the syntax?
Do you support feature reports? In/outgoing? How do you define a fixed length buffer? How do you define the feature report number?
Best mplanck

**Comment by mahmudrazliqli** [comment]
how i can get simplest code only for one device?

**Comment by 452** [comment]
@mahmudrazliqli
you can use this project for start, just fork, and then you can remove all functionality what you want.

receive data from device:
https://github.com/452/USBHIDTerminal/blob/master/src/com/appspot/usbhidterminal/core/services/AbstractUSBHIDService.java#L111
https://github.com/452/USBHIDTerminal/blob/master/src/com/appspot/usbhidterminal/core/services/USBHIDService.java#L80
send data to device:
https://github.com/452/USBHIDTerminal/blob/master/src/com/appspot/usbhidterminal/core/services/AbstractUSBHIDService.java#L148

All functionality for USB HID in this two files:
AbstractUSBHIDService.java
USBHIDService.java
