### ISSUE TITLE
ActivityStarter (App Inventor 2) 

### ISSUE THREAD

**Issue by choperhead** [452/USBHIDTerminal#13]
Hello 452:  i'm Martin from Argentina. I found your USBHIDTerminal here. i'm working on a project to comunicate some hand intrument to a android phone
my question is if it's posible to acceses to the app via an ActivityStarter (or some else) in app inventor 2, to send an recive hid data. 
If it is yes. Can you give me some tips about this?? how can i do.

 i'm so newby in java. 
thank you in advance! 
& sorry my english writing is so bad :-)

Martin

**Comment by 452** [comment]
Hello Martin, I'm from Ukraine)))
I apologize for long time response for your question...
I never use "app inventor" and have no idea if this it possible or not very...
but if this is possible you can do with this app everything you want =) it's open source =)
& sorry my English writing is also so bad :-)), I think our children's will be better speak English then we ;-)
Ihor
