### ISSUE TITLE
I made a tool base on your USBHIDTerminal

### ISSUE THREAD

**Issue by lhy2871** [452/USBHIDTerminal#15]
Hi emetemunoy
I made a HID devices setup tool based on your USBHIDTerminal.
I am also upload the project on github.
Here is the link: https://github.com/lhy2871/EasyncSetupTool4Android
I am new on git hub. I don't know how to fork (tried but not success), so I download your sourcecode and rewrite my on tool.
By the way, I do NOT want the Server part, Just want a simplest tool.
Could you help me to remove the Server part?

Sincerely 
Hanyuan

**Comment by 452** [comment]
Hi Ihy2871 =)))
yes, this is wonderful, I can try to help you for remove server part
this can be maybe in Sunday April 22
# if you want we can make call in hangout share your screen - and I will say how to remove and what
# or I can remove from code in you git repository

**Comment by lhy2871** [comment]
Well, could you please do the change on github?
Because I have class these days.

Hanyuan

**Comment by lhy2871** [comment]
By the way, my English is not well (I am a Chinese man) 
But I'd love to talk to you.

**Comment by 452** [comment]
> Well, could you please do the change on github?
yes, of course
but this can be two days, approximately, because I buy new laptop, and have no Android IDE, etc, today I have installed Android Studio, and I will try to compile your project...

> By the way, my English is not well (I am a Chinese man)
all ok, I also learn English =)

> Hanyuan
it's https://en.wikipedia.org/wiki/Hanyuan_County ? or your name?

> But I'd love to talk to you.
yes, good idea, maybe you can help me with some nice shops in China or and embedded electronics, also it's nice to improve and one more language learning
https://www.facebook.com/emetemunoy
skype: sp_ihor

**Comment by 452** [comment]
@lhy2871 
I have removed webserver and socket part from your sources
https://github.com/452/EasyncSetupTool4Android/commit/a444df8e73ddb87175d5b0a204d00c369eeaba46 you can see changes for that

now you can make pull request

also I have clean your git repo
https://github.com/452/EasyncSetupTool4Android/commit/6747e6781885f1caec2c6e012831a63ba0943209

before pull request, you need test this changes
I have no tested, I just remove server part from code, and build
`./gradlew clean build`
in windows you can use for build
`gradlew.bat clean build`

**Comment by lhy2871** [comment]
I tested the code.
Unfortunately it can not run properly. (the app quit unexpectedly)

**Comment by 452** [comment]
ok, I will debug today, after 8 hours

**Comment by lhy2871** [comment]
Thank you.
Because I really can not find out why it fails.

**Comment by 452** [comment]
@lhy2871
https://github.com/452/EasyncSetupTool4Android/commit/4e1cc0dd195075ea01b553433ac1766044bac4ea
please test again
