### ISSUE TITLE
binary format

### ISSUE THREAD

**Issue by TinyTheBrontosaurus** [452/USBHIDTerminal#16]
Super handy app. I was able to use it to solve my problem almost immediately.

As a first time user, the thing that took me the longest to figure out was how to send binary data. A single number was easy, but i had to open up the code to realize a) it was interpreting the numbers as decimal integers, b) the separator was whitespace. A better description of the radio button labeled "Bytes/0xAB/#AB" would have saved me some time.

**Comment by 452** [comment]
Thank you for improvements =)
