### ISSUE TITLE
"your device is not compatible with this version"

### ISSUE THREAD

**Issue by vinaytumbemane** [452/USBHIDTerminal#7]
I am getting "your device is not compatible with this version" message. I tried to install this app on android powered pcDuino3 board. Android 4.2.2 is installed on pcDuino3. But its unable to detect my USB device. Plz help.

**Comment by 452** [comment]
my Lenovo S930 also not support OTG cable, have no power on device when I try to connect usb flash drive.

You need to check if your android device have support OTG.

"this version" - with previous version your android device have work with USB HID Terminal?

**Comment by vinaytumbemane** [comment]
pcDuino3 has USB2.0 I tried to connect usb device without OTG also. even then it is not recognising.

Even with OTG cable its not recognising usb device.

**Comment by vinaytumbemane** [comment]
Why app is not recognizing mouse and keyboard?

**Comment by 452** [comment]
maybe for this need to select another endPoint - this future on this moment not implemented in USB HID Terminal

by default app work only with endPoint(0) for read and write
you can change in sources to another endPoints

**Comment by vinaytumbemane** [comment]
But for that first it should detect connected USB HID device. When the attached device is detected we can have communication.

**Comment by 452** [comment]
it's true =)

**Comment by vinaytumbemane** [comment]
Hi,
I develeped an Application to read serial data from USB HID device. It works fine on Nexus 7 tablet.
 Now I am trying to read incoming serial data from USB HID device connected to pcDuino3 (Android OS 4.2.2) from my Application. But I am unable to detect the USB HID device from my App. I used USB Host API.

However I am able to detect the device through terminal window.
My Device Details
product ID : 0010
Vender ID : 1658

Here is some observation of my project.
In Terminal emulator When I give command "ls /dev/usb",  I get the following output:

@android: / $ ls/dev/usb
hiddev0
input3-1.1
input3-1.2
input3-1.4


When I give command "busybox lsusb" I get the following output:

@android: / $ busybox lsusb
Bus 001 Device 002 : ID 0bda:8179
Bus 003 Device 002 : ID 1a40:0101
Bus 001 Device 001 : ID 1d6b:0002
Bus 002 Device 001 : ID 1d6b:0001
. . .
. . .
Bus 003 Device 007 : ID 1658:0010

Can any one help me to resolve this problem or enlighten me on what is going on?

**Comment by 452** [comment]
I don't know what is going on =) in your android device:
but you can try to read RAW data via console
http://stackoverflow.com/questions/873975/how-to-capture-raw-hid-input-on-linux

```
cat /dev/usb/hiddev0 - XXX
or /dev/input/uinput
or sudo cat /dev/input/event3 | hexdump
```

or you can try to run python program:
https://play.google.com/store/apps/details?id=com.hipipal.qpyplus
but you need this dependencies usb.util
http://sourceforge.net/projects/pyusb/
http://stackoverflow.com/questions/9577601/detect-the-state-of-a-switch-connected-to-usb-with-python
```python
#!/usr/bin/python
import sys
import re
import usb.core
import usb.util
# decimal vendor and product values
dev = usb.core.find(idVendor=0xf055, idProduct=0x1234)
# first endpoint
interface = 0
endpoint = dev[0][(0,0)][0]
# if the OS kernel already claimed the device, which is most likely true
# thanks to http://stackoverflow.com/questions/8218683/pyusb-cannot-set-configuration
if dev.is_kernel_driver_active(interface) is True:
  # tell the kernel to detach
  dev.detach_kernel_driver(interface)
  # claim the device
  usb.util.claim_interface(dev, interface)
stopflag = 1
collected = 0
#dev.write(1, sys.argv[1], 0, 100)
strout = ''
while stopflag:
    try:
        data = dev.read(endpoint.bEndpointAddress,endpoint.wMaxPacketSize)
        #print data
	sret = ''.join([chr(x) for x in data])
	#print sret
	if sret == 'stop':
		stopflag = 0
	else:
		print sret

    except usb.core.USBError as e:
        data = None
        if e.args == ('Operation timed out',):
            continue
print strout
# release the device
usb.util.release_interface(dev, interface)
# reattach the device to the OS kernel
dev.attach_kernel_driver(interface)
```

**Comment by vinaytumbemane** [comment]
https://play.google.com/store/apps/details?id=hu.sztupy.android.usbhostcontroller&hl=en

Above app detects my device on pcDuino3. But developer mentioned he did not use USB Host API.

**Comment by 452** [comment]
I think this app work via unix commands, like lsusb, etc...
>requires root (superuser) access, and a recent version of busybox installed!
You can find appropriate kernel drivers

**Comment by 452** [comment]
>
It works fine on Nexus 7 tablet.
Now I am trying to read incoming serial data from USB HID device connected to pcDuino3 (Android OS 4.2.2) from my Application. But I am unable to detect the USB HID device from my App. I used USB Host API.

its work fine with USB HID Terminal app on your Nexus 7?
and USB HID Terminal don't work on another android device? - please provide Model of device...

>read serial data from USB HID device

you mean RS-232 serial data or USB HID data?

maybe something wrong with power supply for your HID device from android tablet...?

**Comment by vinaytumbemane** [comment]
It does not work on pcDuino3. "Device is not compatible with this version" warning I get in google play store.

I mean USB HID data.

**Comment by 452** [comment]
can you try to install from binary apk? - https://github.com/452/USBHIDTerminalAPKRepo

**Comment by 452** [comment]
I have no see pcDuino3 in Google play developer console - Supported devices list
https://support.google.com/googleplay/android-developer/answer/1286017

**Comment by vinaytumbemane** [comment]
Even Binary apk is not detecting. When I click on Select HID device alert dialog says "please connect your device"

**Comment by 452** [comment]
so, you need try to check how is work your pcDuino3 with USB HID via terminal
```
cat /dev/usb/hiddev0
```

**Comment by 452** [comment]
>Why app is not recognizing mouse and keyboard?
and when you are connect mouse or keyboard to your pcDuino3 board, mouse work fine?

**Comment by vinaytumbemane** [comment]
yes mouse and keyboard works fine. Even on Nexus 7, USB HID Terminal app will not recognize mouse and keyboard.

Command : cat /dev/usb/hiddev0
output is  cat: /dev/usb/hiddev0 : Permission Denied.

**Comment by 452** [comment]
>
Command : cat /dev/usb/hiddev0
output is cat: /dev/usb/hiddev0 : Permission Denied.

you need root access
```
#to see list of hid devices, try to disconect from board, and connect to board and see changes
sudo ls /dev/usb/
```
try
```
sudo cat /dev/usb/hiddev0
```

sudo cat /dev/usb/hiddevX

X - number of your HID device

**Comment by vinaytumbemane** [comment]
I don't have root access

**Comment by 452** [comment]
http://forum.linksprite.com/index.php?/topic/2833-wireless-keyboardmouse/

maybe this work?
```
 $ su
 # busybox sudo cat /dev/usb/hiddev0
```

**Comment by vinaytumbemane** [comment]
sudo : applet not found
above response i am getting.

Lot of Thanks for the time.. :)

**Comment by 452** [comment]
always happy to help =)

**Comment by vinaytumbemane** [comment]
what do you mean by sudo : applet not found

**Comment by 452** [comment]
this is BusyBox problem, have no executable program:

http://forum.xda-developers.com/showthread.php?t=1691139
http://stackoverflow.com/questions/30442551/busybox-tries-to-execute-every-command-on-embedded?lq=1

**Comment by vinaytumbemane** [comment]
I followed steps explained in answer of following question. but I could not create android.hardware.usb.host.xml file.  I am not able to edit the file. it says read only file system, how can i edit it?
http://stackoverflow.com/questions/11183792/android-usb-host-and-hidden-devices/11992683#11992683

In system/etc/permissions I don't have android.hardware.usb.host.xml file. 

It has android.hardware.usb.accessory.xml file

**Comment by 452** [comment]
you can use ADB https://developer.android.com/tools/help/adb.html
try to search "adb download" for your operation system
for Ubuntu

```sh
sudo apt-get install android-tools-adb android-tools-fastboot
```

for create android.hardware.usb.host.xml in folder /system/etc/permissions:
```sh
vim android.hardware.usb.host.xml
adb push android.hardware.usb.host.xml /system/etc/permissions
```

**Comment by vinaytumbemane** [comment]
I am Using windows 8.
I installed terminal emulator. in that I am trying to create the file. But I am unable to edit and create file in system/etc/permissions

**Comment by 452** [comment]
https://www.youtube.com/watch?v=Ki4MzbftKq0
https://www.youtube.com/watch?v=G9Xsg7DkqN4

http://adbdriver.com/downloads/
http://donandroid.com/how-to-install-adb-interface-drivers-windows-7-xp-vista-623
http://adbdriver.com/documentations/how-to-enable-usb-debugging-mode-on-android-devices.html
http://dottech.org/21534/how-to-install-adb-and-fastboot-on-your-windows-computer-for-use-with-your-android-phone/
http://www.redmondpie.com/how-to-set-up-android-adb-and-fastboot-on-windows-tutorial/

adbdriver.com - I have no checked about this site, maybe it's good one, maybe not.

you just need download adb tools on your PC

go to windows console
cd /path to folder with adb

**Comment by 452** [comment]
https://github.com/grundid/android-weather-station/tree/master/usb-fix

**Comment by 452** [comment]
Also I create Wiki page with this information =)
https://github.com/452/USBHIDTerminal/wiki/How-to-enable-USB-host-API-support

**Comment by vinaytumbemane** [comment]
giving adb command will list all the commands to be used.

in my desktop I have "new folder" containing android.hardware.usb.host.xml file. but i could not write this to permission folder

adb pull /system/etc/permissions/tablet_core_hardware.xml command gives 'adb' is not recognized as internal or external command, operable program or batch file.

**Comment by 452** [comment]
have you Skype?
teamviewer - I can try to connect to your PC and configure your system - you will see All what I can do
https://www.teamviewer.com/en/index.aspx

https://play.google.com/store/apps/details?id=eu.chainfire.supersu&hl=en

**Comment by 452** [comment]
in Windows you need to use adb.exe
```sh
adb.exe pull /system/etc/permissions/tablet_core_hardware.xml
```

in your "new folder" also must be tablet_core_hardware.xml

but before you pull this file into /system/etc/permissions/ directory on your board you need put into tablet_core_hardware.xml file correct data

for this you need

```sh
adb.exe shell
cat /system/etc/permissions/tablet_core_hardware.xml
```

then just copy text from existing tablet_core_hardware.xml file into your "new folder" tablet_core_hardware.xml
and add this line
```xml
<feature name="android.hardware.usb.host" />
```
into your tablet_core_hardware.xml before pull

or change this file with text editor on your device

**Comment by vinaytumbemane** [comment]
I used android terminal app.

$ su

# mount -o remount,rw /system

above command worked. I could able mount the folder. 
then I used
# chmod 666 /filepath

this allows you to change the read only file to read/write file.
as soon as you make change and save it revert the file to read only. 

unfortunately everything got erased now. again I need to install the OS and proceed further.
I will update complete procedure I followed once I do everything

**Comment by vinaytumbemane** [comment]
Hi,
Finally I found a solution for this problem. 
Android application running on pcDuinoV3 was unable to detect the USB HID device connected to USB Host port.
Reason : File named "android.hardware.usb.host.xml" is not present in system/etc/permissions folder.
Steps followed to solve the issue:

1. Root the pcDuino3
2. Install Terminal Emulator for Android. ( https://play.google.com/store/apps/details?id=jackpal.androidterm )
3. Open a terminal window and become the superuser
4. The file system may be read-only, so you might have to remount it.
5. Then Change the mode to read/write.
6. the file system may be read-only, so you might have to remount it
7. To enable USB host API support you should add a file named android.hardware.usb.host.xml and containing the following lines:

<?xml version="1.0" encoding="utf-8"?>

<permissions>
<feature name="android.hardware.usb.host"/>
</permissions>

into folder: /system/etc/permissions

8. In the folder: /system/etc/permissions
   you will find file named: "handheld_core_hardware.xml" or "tablet_core_hardware.xml"
  
   add: <feature name="android.hardware.usb.host" />
   inside: <permissions> 

            </permissions>

 9. Reboot your device. 

After this My Application detected USB HID device.

Link to related question and answer:
http://stackoverflow.com/questions/11183792/android-usb-host-and-hidden-devices/11992683#11992683
