### ISSUE TITLE
Making this work with POS printers 

### ISSUE THREAD

**Issue by Jesusrz001** [452/USBHIDTerminal#8]
Think this would be a relevant feature?

**Comment by 452** [comment]
what model of POS  printer?
this POS printer support USB HID protocol?

**Comment by Jesusrz001** [comment]
Communicating between EPSON POS printers

On Wed, Jun 3, 2015 at 1:28 PM, emetemunoy <notifications@github.com> wrote:

> what model of POS printer?
> this POS printer support USB HID protocol?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/452/USBHIDTerminal/issues/8#issuecomment-108562355>.
>



-- 
Jesus Rodriguez

**Comment by 452** [comment]
need more information about printer model, and specification of communication with this model, can you provide more info and links?

**Comment by Jesusrz001** [comment]
http://www.pos-x.com/EVO-Green-p101.aspx Use EPSON printer control code to my knowledge. Wondering whether we would need a driver pack or if we can create an interface

**Comment by 452** [comment]
you need USB Serial protocol(RS-232) not USB HID

https://github.com/mik3y/usb-serial-for-android

https://play.google.com/store/apps/details?id=jp.ksksue.app.terminal
https://play.google.com/store/apps/details?id=com.liorhass.android.usbterminal.free
